package com.eventops.domain.audit;

/**
 * Audit log action categories.
 */
public enum AuditActionType {
    // Auth
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    ACCOUNT_CREATED,
    ACCOUNT_LOCKED,
    PASSWORD_CHANGED,

    // Registration
    REGISTRATION_CREATED,
    REGISTRATION_CANCELLED,
    WAITLIST_JOINED,
    WAITLIST_PROMOTED,
    WAITLIST_EXPIRED,

    // Check-in
    CHECKIN_SUCCESS,
    CHECKIN_DENIED,
    DEVICE_BOUND,
    DEVICE_CONFLICT_WARNING,

    // Notification
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED,
    SUBSCRIPTION_CHANGED,

    // Finance
    POSTING_CREATED,
    POSTING_REVERSED,
    ALLOCATION_RULE_CREATED,
    ALLOCATION_RULE_UPDATED,
    ACCOUNTING_PERIOD_OPENED,
    ACCOUNTING_PERIOD_CLOSED,

    // Import
    IMPORT_STARTED,
    IMPORT_COMPLETED,
    IMPORT_FAILED,
    CIRCUIT_BREAKER_TRIPPED,

    // Admin
    USER_ROLE_CHANGED,
    SECURITY_SETTING_CHANGED,
    EXPORT_GENERATED,
    EXPORT_DENIED,
    BACKUP_EXECUTED,
    BACKUP_RETENTION_CLEANUP
}
