import { describe, it, expect, vi, beforeEach } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import { createPinia, setActivePinia } from 'pinia'

vi.mock('../../src/api/admin.js', () => ({
  listUsers: vi.fn(), createUser: vi.fn(), updateUser: vi.fn(),
  getSecuritySettings: vi.fn(), updateSecuritySettings: vi.fn(),
  listAuditLogs: vi.fn(), getAuditLog: vi.fn(), exportAuditLogs: vi.fn(), downloadAuditExport: vi.fn(),
  listBackups: vi.fn(), getBackup: vi.fn(), triggerBackup: vi.fn(), getRetentionStatus: vi.fn()
}))
vi.mock('../../src/api/imports.js', () => ({
  listSources: vi.fn(), createSource: vi.fn(), updateSource: vi.fn(),
  listJobs: vi.fn(), getJob: vi.fn(), triggerCrawl: vi.fn(), getCircuitBreakerStatus: vi.fn()
}))
vi.mock('../../src/api/exports.js', () => ({
  exportRoster: vi.fn(),
  exportFinanceReport: vi.fn(),
  downloadExport: vi.fn(),
  getExportPolicies: vi.fn(),
  updateExportPolicies: vi.fn()
}))

import { getExportPolicies, exportRoster, exportFinanceReport } from '../../src/api/exports.js'
import { exportAuditLogs } from '../../src/api/admin.js'
import ExportDashboardView from '../../src/views/exports/ExportDashboardView.vue'
import { useAuthStore } from '../../src/stores/auth.js'

async function mountView({ role = 'EVENT_STAFF' } = {}) {
  const pinia = createPinia()
  setActivePinia(pinia)
  const auth = useAuthStore()
  auth.user = { id: 'u1', roleType: role }
  return mount(ExportDashboardView, { global: { plugins: [pinia] } })
}

describe('ExportDashboardView', () => {
  beforeEach(() => { vi.clearAllMocks() })

  it('denies access for attendee users', async () => {
    const wrapper = await mountView({ role: 'ATTENDEE' })
    expect(wrapper.text()).toContain('Access Denied')
  })

  it('shows watermark notice after init', async () => {
    getExportPolicies.mockResolvedValue({ data: { data: [] } })
    const wrapper = await mountView()
    await flushPromises()
    expect(wrapper.text()).toContain('watermarked with operator identity')
  })

  it('export roster success shows Job ID', async () => {
    getExportPolicies.mockResolvedValue({ data: { data: [] } })
    exportRoster.mockResolvedValue({ data: { data: { id: 'job-1', status: 'COMPLETE' } } })
    const wrapper = await mountView()
    await flushPromises()
    await wrapper.find('#roster-session').setValue('sess-1')
    await wrapper.findAll('form')[0].trigger('submit.prevent')
    await flushPromises()
    expect(exportRoster).toHaveBeenCalledWith({ sessionId: 'sess-1' })
    expect(wrapper.text()).toContain('job-1')
  })

  it('export finance success shows Job ID', async () => {
    getExportPolicies.mockResolvedValue({ data: { data: [] } })
    exportFinanceReport.mockResolvedValue({ data: { data: { id: 'fj-1', status: 'COMPLETE' } } })
    const wrapper = await mountView()
    await flushPromises()
    await wrapper.find('#finance-period').setValue('p1')
    await wrapper.findAll('form')[1].trigger('submit.prevent')
    await flushPromises()
    expect(exportFinanceReport).toHaveBeenCalledWith({ periodId: 'p1' })
    expect(wrapper.text()).toContain('fj-1')
  })

  it('export audit success shows exportId', async () => {
    getExportPolicies.mockResolvedValue({ data: { data: [] } })
    exportAuditLogs.mockResolvedValue({ data: { data: { exportId: 'ae-1' } } })
    const wrapper = await mountView()
    await flushPromises()
    await wrapper.find('#audit-from').setValue('2026-01-01')
    await wrapper.find('#audit-to').setValue('2026-03-31')
    await wrapper.findAll('form')[2].trigger('submit.prevent')
    await flushPromises()
    expect(exportAuditLogs).toHaveBeenCalled()
    expect(wrapper.text()).toContain('ae-1')
  })

  it('renders policy rows when policies present', async () => {
    getExportPolicies.mockResolvedValue({
      data: {
        data: [
          { id: 'pol-1', reportType: 'ROSTER', roleType: 'EVENT_STAFF', downloadAllowed: true, watermarkTemplate: 'generated by ...' }
        ]
      }
    })
    const wrapper = await mountView()
    await flushPromises()
    expect(wrapper.text()).toContain('ROSTER')
    expect(wrapper.text()).toContain('EVENT STAFF')
  })
})
