package com.eventops.common.dto;

public enum ConflictType {
    DUPLICATE_REGISTRATION,
    QUOTA_EXCEEDED,
    WINDOW_CLOSED,
    DEVICE_CONFLICT,
    CONCURRENT_DEVICE,
    DUPLICATE_CHECKIN,
    IDEMPOTENCY_DUPLICATE,
    PERIOD_CLOSED,
    RULE_VERSION_CONFLICT
}
