package com.eventops.integration;

import com.eventops.integration.export.CsvGenerator;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class CsvGeneratorTest {

    private static List<String[]> rows(String[]... entries) {
        List<String[]> list = new ArrayList<>();
        Collections.addAll(list, entries);
        return list;
    }

    @Test
    void writeCsv_withWatermark_prependsHeaderBeforeColumns() throws IOException {
        StringWriter writer = new StringWriter();
        CsvGenerator.writeCsv(writer, "# Generated by EventOps",
                new String[]{"Name", "Email"},
                rows(new String[]{"Alice", "alice@example.com"}));
        String output = writer.toString();
        assertTrue(output.startsWith("# Generated by EventOps\n"));
        assertTrue(output.contains("Name,Email\n"));
        assertTrue(output.contains("Alice,alice@example.com\n"));
    }

    @Test
    void writeCsv_withoutWatermark_omitsHeader() throws IOException {
        StringWriter writer = new StringWriter();
        CsvGenerator.writeCsv(writer, null,
                new String[]{"Id", "Value"},
                rows(new String[]{"1", "hello"}));
        String output = writer.toString();
        assertTrue(output.startsWith("Id,Value\n"));
        assertFalse(output.contains("#"));
    }

    @Test
    void writeCsv_emptyRows_writesOnlyHeaders() throws IOException {
        StringWriter writer = new StringWriter();
        CsvGenerator.writeCsv(writer, null, new String[]{"Col1", "Col2"}, Collections.emptyList());
        assertEquals("Col1,Col2\n", writer.toString());
    }

    @Test
    void writeCsv_fieldWithComma_isQuoted() throws IOException {
        StringWriter writer = new StringWriter();
        CsvGenerator.writeCsv(writer, null,
                new String[]{"Name"},
                rows(new String[]{"Doe, John"}));
        assertTrue(writer.toString().contains("\"Doe, John\""));
    }

    @Test
    void writeCsv_fieldWithDoubleQuote_isEscapedAndQuoted() throws IOException {
        StringWriter writer = new StringWriter();
        CsvGenerator.writeCsv(writer, null,
                new String[]{"Desc"},
                rows(new String[]{"She said \"hello\""}));
        assertTrue(writer.toString().contains("\"She said \"\"hello\"\"\""));
    }

    @Test
    void writeCsv_fieldWithNewline_isQuoted() throws IOException {
        StringWriter writer = new StringWriter();
        CsvGenerator.writeCsv(writer, null,
                new String[]{"Address"},
                rows(new String[]{"Line1\nLine2"}));
        assertTrue(writer.toString().contains("\"Line1\nLine2\""));
    }

    @Test
    void writeCsv_nullField_replacedWithEmpty() throws IOException {
        StringWriter writer = new StringWriter();
        CsvGenerator.writeCsv(writer, null,
                new String[]{"A", "B"},
                rows(new String[]{"val", null}));
        assertTrue(writer.toString().contains("val,\n"));
    }

    @Test
    void writeCsv_multipleRows_allWritten() throws IOException {
        StringWriter writer = new StringWriter();
        CsvGenerator.writeCsv(writer, null,
                new String[]{"X"},
                rows(new String[]{"a"}, new String[]{"b"}, new String[]{"c"}));
        String[] lines = writer.toString().split("\n");
        assertEquals(4, lines.length);
    }
}
