package com.eventops.service;

import com.eventops.domain.audit.WatermarkPolicy;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ExportPolicyTest {

    @Test
    void defaultPolicy_allowsDownload() {
        WatermarkPolicy policy = new WatermarkPolicy();
        assertTrue(policy.isDownloadAllowed(), "Default should allow downloads");
    }

    @Test
    void policy_canDenyDownload() {
        WatermarkPolicy policy = new WatermarkPolicy();
        policy.setDownloadAllowed(false);
        assertFalse(policy.isDownloadAllowed());
    }

    @Test
    void watermarkTemplate_storedCorrectly() {
        WatermarkPolicy policy = new WatermarkPolicy();
        policy.setWatermarkTemplate("Generated by: {{operator}} at {{timestamp}}");
        assertEquals("Generated by: {{operator}} at {{timestamp}}", policy.getWatermarkTemplate());
    }

    @Test
    void policy_hasBothReportTypeAndRole() {
        WatermarkPolicy policy = new WatermarkPolicy();
        policy.setReportType("AUDIT_LOG");
        policy.setRoleType("SYSTEM_ADMIN");
        assertEquals("AUDIT_LOG", policy.getReportType());
        assertEquals("SYSTEM_ADMIN", policy.getRoleType());
    }
}
